### ISSUE TITLE
Add more precise methods

### ISSUE THREAD

**Issue by an-Iceberg** [imrn99/integraal#23]
### Information

- [ ] Question
- [x] Suggestion
- [ ] Other: ...

The trapezoid and rectangle methods are known to be very imprecise and computationally expensive compared to the error they produce. (T = trapezoid method, R = rectangle method, S = Simpson's ⅓ rule)

![image](https://github.com/user-attachments/assets/43a2db2a-252c-47e8-bb69-5ed02834d495)

Other methods achieve far greater precision with often far less computation effort.

### Content

Requesting the following integration methods to be added:
- [Simpson's ⅓ rule](https://en.wikipedia.org/wiki/Simpson%27s_rule#Composite_Simpson's_1/3_rule)
- [Simpson's ⅜ rule](https://en.wikipedia.org/wiki/Simpson%27s_rule#Composite_Simpson's_3/8_rule)
- [Boole's rule](https://en.wikipedia.org/wiki/Boole%27s_rule)
- [Romberg extrapolation](https://en.wikipedia.org/wiki/Romberg%27s_method)

---

For the Simpson's ⅓ rule i have this formula from my math script that appears to be more precise than the one on Wikipedia according to my own testing:

![image](https://github.com/user-attachments/assets/ff918c27-e44b-4bb9-9dd1-96f8006c85b2)

Where ![image](https://github.com/user-attachments/assets/3bc6ace6-33bf-4d5e-8719-29457a80080c)

`h` is the width of a segment.

---

If i find time in the future i may look to implement some of them myself & create a pull request b/c this project appears to have an interesting interface.

**Comment by imrn99** [comment]
Thank you for your interest!

> The trapezoid and rectangle methods are known to be very imprecise and computationally expensive compared to the error they produce. (T = trapezoid method, R = rectangle method, S = Simpson's ⅓ rule)
> 
> ...
> 
> Other methods achieve far greater precision with often far less computation effort.

I started this project because I wanted to experiment with the builder pattern & idiomatic computation routines; I'm not very knowledgeable about numerical integration in the first place. That being said, I would be interested in implementing better methods.
 
> Requesting the following integration methods to be added:
> 
>  ...

From what I can see, the Simpson's ⅓ rule seems easy enough to implement so I'll give it a try.

The main issue I have would be in the implementation of `Integraal::compute_error`, which requires n-th derivative approximation for most of the methods you mentioned.
The code approximating the second derivative is already a mess, so I'll have to rewrite this properly before implementing any more error estimations.

I'll try to work on a first new method implementation while ignoring the error approximation for now, no ETA to give though.

**Comment by an-Iceberg** [comment]
If you want to do numerical derivation i can recommend the [finite difference method (FCM)](https://en.wikipedia.org/wiki/Finite_difference_coefficient) or h² extrapolation (which is basically the same as Romberg extrapolation).

The thing about the FCM is that if you chose your coefficients poorly your calculations will be subject to numerical instability and cancellation. Thus, a popular way to not make the coefficients fractions is by multiplying the whole expression with a factor.

Here's a little example i've whipped up.
```rust
fn main()
{
  println!(" df/dx = {}", d(f, x, h));
  println!("     ε = {:.2e}", (d(f, x, h) - f1(x)).abs());
  println!("_df/dx = {}", _d(f, x, h));
  println!("     ε = {:.2e}", (_d(f, x, h) - f1(x)).abs());

  // Output on my machine (yours may be slightly different):
  //  df/dx = 2.9999999999996696
  //      ε = 3.30e-13
  // _df/dx = 2.9999999999996696
  //      ε = 3.30e-13
}

/// First order derivative of a function `f` at location `x` using precision `h`.
///
/// The method is the finite difference using accuracy 2.
#[allow(clippy::needless_return)]
fn d(f: fn(f64) -> f64, x: f64, h: f64) -> f64
{
  return (-0.5*f(x-h) + 0.5*f(x+h)) / h;
}

// Same result, but no fractions.
#[allow(clippy::needless_return)]
fn _d(f: fn(f64) -> f64, x: f64, h: f64) -> f64
{
  return (-f(x-h) + f(x+h)) / (2.*h);
}

/// Second order derivative of a function `f` at `x` using precision `h`.
///
/// The method is the finite difference using accuracy 2.
#[allow(clippy::needless_return)]
fn d2(f: fn(f64) -> f64, x: f64, h: f64) -> f64
{
  return (f(x-h) - (2.*f(x)) + f(x+h)) / h.powi(2);
}
```
I'm also working on and off on a numerical library in Rust and i've decided that it'd be best to pass in the degree (or order) of derivation as the first argument.
So, something like this:
```rust
pub fn d(degree: u8, f: fn(f64) -> f64, x: f64, options: Options) -> f64
```
`options` would be a `struct` where you pass all the options you want into (method, precision, etc.) and i plan to do it similarly integration asw.

---

Here's an implementation of the Simpson's ⅓ i've made a while back:
```rust
#[allow(clippy::needless_return)]
pub fn simpson(f: fn(f64) -> f64, a: f64, b: f64, h: Option<f64>) -> f64
{
  let mut _h = 1e-3;
  // If h was supplied, take it, otherwise use the sensible “default”
  if let Some(h) = h { _h = h }
  // Calculates the amount of segments we need to sum over
  let n = ((b - a) / _h).ceil() as u64;

  #[allow(non_snake_case)]
  let (mut Σ1, mut Σ2) = (0., 0.);

  let x = |i| a + (i as f64 * _h);

  for i in 1..n { Σ1 += f(x(i)) }
  for i in 1..=n { Σ2 += f((x(i-1) + x(i)) / 2.) }

  return (_h/3.)*((f(a)/2.) + Σ1 + (2.*Σ2) + (f(b)/2.));
}
```

---

Tho i don't know why you'd want to compute the error; that is only possible if you have the analytical solution for the function you're trying to integrate.
You'd basically try to use an error-prone method to find the error of another error-prone method.

**Comment by imrn99** [comment]
> Here's an implementation of the Simpson's ⅓ i've made a while back:
> 
> ```rust
> #[allow(clippy::needless_return)]
> pub fn simpson(f: fn(f64) -> f64, a: f64, b: f64, h: Option<f64>) -> f64
> {
>   let mut _h = 1e-3;
>   // If h was supplied, take it, otherwise use the sensible “default”
>   if let Some(h) = h { _h = h }
>   // Calculates the amount of segments we need to sum over
>   let n = ((b - a) / _h).ceil() as u64;
> 
>   #[allow(non_snake_case)]
>   let (mut Σ1, mut Σ2) = (0., 0.);
> 
>   let x = |i| a + (i as f64 * _h);
> 
>   for i in 1..n { Σ1 += f(x(i)) }
>   for i in 1..=n { Σ2 += f((x(i-1) + x(i)) / 2.) }
> 
>   return (_h/3.)*((f(a)/2.) + Σ1 + (2.*Σ2) + (f(b)/2.));
> }
> ```

Thanks, that's a good starting point

> Tho i don't know why you'd want to compute the error; that is only possible if you have the analytical solution for the function you're trying to integrate. You'd basically try to use an error-prone method to find the error of another error-prone method.

The idea was to have an estimation of the error to use in tests, but considering the hassle it is, I might cut it from the crate

**Comment by an-Iceberg** [comment]
> The idea was to have an estimation of the error to use in tests, but considering the hassle it is, I might cut it from the crate

That makes sense, tho for testing you can simply use the analytical integral/derivative of the function to get the absolute error. That's kinda how i do it in my tests too.

```rust
let f = |x: f64| x.powi(2);
#[allow(non_snake_case)]
let F = |x: f64| (1./3.)*x.powi(3);
let a = 1.;
let b = 5.;
let h = 1e-3;

println!("ε = {:.2e}", (simpson(f, a, b, Some(h)) - (F(b) - F(a))).abs());

// Output on my machine:
// ε = 2.13e-14
```

Also, check out the [`nearly`](https://crates.io/crates/nearly) crate. Really handy for comparing floating point numbers for equality.

**Comment by imrn99** [comment]
hey,

I implemented the following additional methods: 
- simpson's rule (a mix of different variants depending on inputs)
- romberg's method
- boole's method

This is a good base for now, I'll go over the documentation & tests once more before closing this issue, unless there's something else you request

**Comment by an-Iceberg** [comment]
I'm very busy with my studies atm so i can't respond. But don't feel pressured b/c of me, it's your project after all; i just posted an idea.

I don't have anything else regarding this issue. If i'll find something else i'll open a new one.
